[package]
name = "fin"
version = "0.1.0"
edition = "2024"

[dependencies]
tempulse-core = { path = "../../crates/core" }
tempulse-storage = { path = "../../crates/storage" }
tempulse-tempo = { path = "../../crates/tempo" }

alloy = { version = "1.6.3", features = ["full"] }
tempo-alloy = { git = "https://github.com/tempoxyz/tempo", tag = "v1.1.2" }

eyre = "0.6"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros", "signal"] }
tracing = "0.1"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres"] }
hex = "0.4"
